apiVersion: v1
kind: LimitRange
metadata:
  name: maxmin
spec:
  limits:
    - max:
        memory: 1Gi
      min:
        memory: 500Mi
    - max: 
        cpu: 1m
      min:
        cpu: 0.5m