apiVersion: v1
kind: ReplicaSet
metadata:
  name: frontend
  labels:
    app: frontend
    tier: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        tier: frontend
  spec:
    containers:
      - image:  nginx
        name:  frontend
      
