apiVersion: v1
kind: pod
metadata:
  name: memory-limit
spec:
  containers:
    - image:  nginx
      name:  memorydemo
  resources:
    limits:
      memory: 1Gi
    request:
      memory: 400Mi